### ISSUE TITLE
Implement legacy eRO creator plants and marine spheres

### ISSUE THREAD

**Issue by ajlkqwe** [korsiakk/EssenceRO-Bug-Tracker#12]

**Comment by korsiakk** [comment]
I would love to see this in.

**Comment by ajlkqwe** [comment]
Updated in korsiakk/EssenceRO2020@1cf2a85ec342f3873525e277898bd5b3e4dd49cb and korsiakk/EssenceRO2020@39874867408ee56b75c928f652e12a8baa14feb1
