### ISSUE TITLE
Make Exploding Dragon (a.k.a. Dragon Fire Formation) go through Land Protector.

### ISSUE THREAD

**Issue by jonskie1218** [korsiakk/EssenceRO-Bug-Tracker#2]
Maybe it's more of making NON-GROUND TARGETED AOE SPELLS go through Land Protector.

It's basically like North Wind, Focused Arrow Strike, Fireball, etc.

**Comment by korsiakk** [comment]
This mostly pertains to Ninja Skills.  Currently they're not piercing LP as they are originally intended.

**Comment by ajlkqwe** [comment]
Fixed by jacexor in korsiakk/EssenceRO2020@b7cf29a3d236b20972669a0a1fceda5273246eba
