### ISSUE TITLE
White Slim Potions weight incorrect

### ISSUE THREAD

**Issue by wickywickywoo** [korsiakk/EssenceRO-Bug-Tracker#3]
White slims (aka condensed white potion) currently have a weight of 5, despite their description saying 2.

http://divine-pride.net/database/item/547/condensed-white-potion
http://ratemyserver.net/item_db.php?item_id=547&small=1&back=1

**Comment by korsiakk** [comment]
Fixed in Client Update initiated 4-19-2020
