### ISSUE TITLE
Misleading description of the Schwartzwald Pine Jubilee item.

### ISSUE THREAD

**Issue by MiragaGoW** [korsiakk/EssenceRO-Bug-Tracker#35]
The item's description mentions the following stats given to the user when consumed:
+10 Hit
+20 Flee

But instead of the +20 Flee, the user is given +20 Perfect Dodge (which is also mentioned on the RMS site).

**Comment by ajlkqwe** [comment]
Effect adjusted to 5 PD.  Description still to be updated.

**Comment by ajlkqwe** [comment]
The description update seems to be in.  Closing this.
