### ISSUE TITLE
"Blocked" damage are reflectable.

### ISSUE THREAD

**Issue by MiragaGoW** [korsiakk/EssenceRO-Bug-Tracker#36]
While endowed with the ability to reflect physical damage (Reflect Shield for instance), when the user blocks an attack with Satefy wall, Parry, Kyrie Elison by example, the attacker still receives the damage.

**Comment by ajlkqwe** [comment]
Emulator bug, the potential for abuse with this is low.  Labeling `won't fix` and closing until a high-impact case is identified.
