### ISSUE TITLE
Guarana Candy's "Concentration Potion" effect does not stack with Awakening/Berserk Potion.

### ISSUE THREAD

**Issue by MiragaGoW** [korsiakk/EssenceRO-Bug-Tracker#39]
Refer to title.

**Comment by ajlkqwe** [comment]
Not sure it's intended to stack with Awakening/Berserk Potion given that a Concentration Potion does not stack with either of those potions.

**Comment by ajlkqwe** [comment]
Guarana Candy ASPD bonus is the same as the Concentration Potion.
http://forum.ratemyserver.net/general-discussion/stackable-aspd-pots/
https://www.limitro.com/forums/reportcenter/itembugs/guarana-candy-buff-bug-r2113/

Visually they appear to stack but ASPD pots have always appeared to visually count while only the highest tier one is functional.  There are balance concerns as well if we were to enable stacking of ASPD potions.
