### ISSUE TITLE
Job level bonus Dex on Ninja offers 6 instead of 10 when job level is maxed.

### ISSUE THREAD

**Issue by MiragaGoW** [korsiakk/EssenceRO-Bug-Tracker#42]
Refer to the wiki: https://wiki.essencero.net/index.php/Ninja_Class_Changes

**Comment by ajlkqwe** [comment]
![image](https://user-images.githubusercontent.com/60751287/79409326-a8e48c00-7f6b-11ea-91cc-2cf79ce5fbc5.png)
![image](https://user-images.githubusercontent.com/60751287/79409344-b39f2100-7f6b-11ea-80d8-c9aabba21142.png)
Fixed in korsiakk/EssenceRO2020@`ad8e61a`
