### ISSUE TITLE
Super Novice/Baby job level used to be of 130 back in eRO v1-2.

### ISSUE THREAD

**Issue by MiragaGoW** [korsiakk/EssenceRO-Bug-Tracker#50]
![image](https://user-images.githubusercontent.com/63676463/79628611-6ad49d00-8110-11ea-8787-cc9ac02a579e.png)

**Comment by ajlkqwe** [comment]
Fixed in korsiakk/EssenceRO2020@09b07a27993cc3cc5236f33edc97205d84cf4ca4
