### ISSUE TITLE
Using Cure to cleanse Eswoo also removes devotion

### ISSUE THREAD

**Issue by wickywickywoo** [korsiakk/EssenceRO-Bug-Tracker#52]
If you successfully cleanse a target of eswoo using the skill cure while they are also being devo'd, the target also loses their devo line. I believe this is a side effect of the forced refresh or teleport that happens when cure successfully cleanses eswoo.

It's worth noting that this refresh/teleport behavior on cure only happens if the target actually has eswoo.

**Comment by ajlkqwe** [comment]
Fixed in korsiakk/EssenceRO2020@b86171c818e4a5b6d3543c6c5f74bcc1aa5e9158
