### ISSUE TITLE
Novice's Adventurer Suit [1] offers the user 45 Hard Defense when equipped.

### ISSUE THREAD

**Issue by MiragaGoW** [korsiakk/EssenceRO-Bug-Tracker#57]
![image](https://user-images.githubusercontent.com/63676463/79692983-27744e80-8236-11ea-8d32-99de97d258b2.png)
![image](https://user-images.githubusercontent.com/63676463/79692989-2f33f300-8236-11ea-9d3b-4f7fccf80fb7.png)

**Comment by ajlkqwe** [comment]
Fixed in korsiakk/EssenceRO2020@9ab7feaa750d3559d5be5a9a32d7ab48f4f780fa
