### ISSUE TITLE
Taekwon's Job Level is capped at 50.

### ISSUE THREAD

**Issue by MiragaGoW** [korsiakk/EssenceRO-Bug-Tracker#61]
This kind of leaves an issue where the Baphomet Horn's ATK from the Job level is rather low and a non-ranker taekwon is stuck with a low amount of points for its skills.
Im unable to confirm its previous Jlvl cap (eRO V1-2), but it was over 50 for certain.

**Comment by phuchduong** [comment]
Old eRO let them go to 70 I believe.

**Comment by ajlkqwe** [comment]
Set to 90 in korsaikk/EssenceRO2020@159b65a7356f375304a74f74040ef6af41ad3bcb
